name: openViewF1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.2.3
  hive_ce: ^2.4.4
  hive_ce_flutter: ^2.0.0
  http: ^1.2.2
  intl: ^0.19.0
  jiffy: ^6.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flags/